### ISSUE TITLE
Problem with calling write_ipynb_local_js()

### ISSUE THREAD

**Issue by mnowotka** [jakevdp/mpld3#292]
Hi,

When I do this:

    Python 2.7.5 (default, Jun 17 2014, 18:11:42) 
    [GCC 4.8.2 20140120 (Red Hat 4.8.2-16)] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import mpld3
    >>> mpld3.utils.write_ipynb_local_js()

I'm getting this:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/python2.7/site-packages/mpld3/utils.py", line 113, in write_ipynb_local_js
    install_nbextension([d3_src, mpld3_src])
      File "/usr/lib/python2.7/site-packages/IPython/html/nbextensions.py", line 179, in install_nbextension
    raise TypeError("path must be a string pointing to a single extension to install; call this function multiple times to install multiple extensions")
    TypeError: path must be a string pointing to a single extension to install; call this function multiple times to install multiple extensions

**Comment by jakevdp** [comment]
Thanks. This looks like an issue with IPython version 3.0: the call signature of ``IPython.html.install_nbextension`` has changed. I'll mark it as a bug. If you come up with a fix, a pull request would be appreciated!

**Comment by mnowotka** [comment]
I'm guessing the fix would be checking for IPython version and if it's IPython 3 callling `IPython.html.install_nbextension` in the loop for every path string instead of providing it all at once.

**Comment by aflaxman** [comment]
@mnowotka : Can you see if #336 has fixed this for you?

**Comment by mnowotka** [comment]
Sure, will do and let you know. Thanks!

**Comment by mnowotka** [comment]
OK, so I have mpld3 0.2 (that's the latest available from conda) and the problem still exists.

**Comment by etgalloway** [comment]
The fix is in master,  not 0.2.

**Comment by mnowotka** [comment]
Right, are you planning to release?

**Comment by etgalloway** [comment]
You need to talk to @jakevdp.
