### ISSUE TITLE
``mpld3.show()`` fails in Python 3.4

### ISSUE THREAD

**Issue by gerardenjuanes** [jakevdp/mpld3#328]
Is this fixed yet? I just tried the example from the Quick Start Guide with the 0.2 release properly installed:

```
import matplotlib.pyplot as plt, mpld3
plt.plot([3,1,4,1,5], 'ks-', mec='w', mew=5, ms=20)
mpld3.show()
```

And I get this:

```
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 1804)
----------------------------------------

stopping Server...
127.0.0.1 - - [29/Oct/2015 15:26:48] "GET / HTTP/1.1" 200 -
Traceback (most recent call last):
  File "C:\Users\Gerard.SEVEN64SOFT01\Anaconda3\lib\socketserver.py", line 305, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\Gerard.SEVEN64SOFT01\Anaconda3\lib\socketserver.py", line 331, in process_request
    self.finish_request(request, client_address)
  File "C:\Users\Gerard.SEVEN64SOFT01\Anaconda3\lib\socketserver.py", line 344, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\Gerard.SEVEN64SOFT01\Anaconda3\lib\socketserver.py", line 673, in __init__
    self.handle()
  File "C:\Users\Gerard.SEVEN64SOFT01\Anaconda3\lib\http\server.py", line 398, in handle
    self.handle_one_request()
  File "C:\Users\Gerard.SEVEN64SOFT01\Anaconda3\lib\http\server.py", line 386, in handle_one_request
    method()
  File "C:\Users\Gerard.SEVEN64SOFT01\Anaconda3\lib\site-packages\mpld3\_server.py", line 38, in do_GET
    self.wfile.write("<html><head>"
  File "C:\Users\Gerard.SEVEN64SOFT01\Anaconda3\lib\socket.py", line 394, in write
    return self._sock.send(b)
TypeError: 'str' does not support the buffer interface
```

So I guess it's not. Is it going to be in the next release? When will that be? 
Thanks, I'll really like to try this tool, looks awesome :)

**Comment by jakevdp** [comment]
This is fixed in master, but the fix has not made it into a release yet. See https://github.com/jakevdp/mpld3/issues/196

We're working on getting a new release, but stalled by javascript test failures that none of the devs know how to debug: https://github.com/jakevdp/mpld3/issues/311
