### ISSUE TITLE
JSON serialization error in mpld3.save_html()

### ISSUE THREAD

**Issue by ajthomas1949** [jakevdp/mpld3#329]
As an experiment, I executed the sample PCA code code from skikit-learn (http://scikit-learn.org/stable/auto_examples/decomposition/plot_pca_iris.html#example-decomposition-plot-pca-iris-py), replacing plot.show() at the end with mpld3.save_html(fig,'PCA.html'). This generates the following error:
Traceback (most recent call last):
  File "irisPCA.py", line 59, in <module>
    mpld3.save_html(fig,'PCA.html')
  File "/usr/local/lib/python2.7/dist-packages/mpld3/_display.py", line 432, in save_html
    fileobj.write(fig_to_html(fig, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/mpld3/_display.py", line 236, in fig_to_html
    figure_json=json.dumps(figure_json),
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: array([-4.,  5.]) is not JSON serializable

This is my first attempt to use mpld3, so please excuse me if I've done something stupid! It looks really nice.

**Comment by gerardodiego** [comment]
I remember I had this problem when I was using Django. It dissapeared when
I downgraded the version of Django.

**Comment by aflaxman** [comment]
`mpld3` does not currently support 3d plotting.  It would be a welcome addition, but probably very difficult.  See past discusion on this here: https://github.com/jakevdp/mpld3/pull/213#issuecomment-51614366
