### ISSUE TITLE
mpld3 displays blank page

### ISSUE THREAD

**Issue by rcrowe123** [jakevdp/mpld3#353]
I'm using matplotlib and mpld3 to display some charts in my django framework. I have the charts working fine in matplotlib (fig.savefig('/tmp/trend.svg'), but when I change it to mpld3.show(fig) or save_html(fig,'/tmp/trend.html'), I get a blank page.

The show command launches the server and brings up a browser, but the page is blank. Same when I save as html, blank page. If you view source on the page I see lots of mpld3 js. What am I missing. I've not used mpld3 before, but have used matplotlib quite a bit. matplotlib version = 1.3.1 mpld3 version = 0.2
This is just a multi-line graph with dates as the x-axis and displays/saves fine with just matplotlib.
Here is the code snippet. You can see all of the methods (various ones commented out)I have used to try and test this.
`for bs in g_bs:
        for qd in g_qd:
            graph_data = []
            graph_dates = []
            for k,v in sorted(workloads[io_type][str(bs)+'_'+str(qd)].iteritems()):
                graph_dates.append(k)
                if io_type == 'randrw70':
                    graph_data.append(v['read_iops']+v['write_iops'])
                else:
                    graph_data.append(v[data_point])
            plt.gca().xaxis.set_major_formatter(mdates.DateFormatter("%Y-%m-%d"))
            plt.plot(graph_dates, graph_data, label=qd, color=colors[g_qd.index(qd)])
            plt.gcf().autofmt_xdate()
        plt.xticks(graph_dates)
        plt.legend(title='QD', loc='upper right')        
        plt.title(io_type+' '+str(bs))
        plt.ylabel(label)
        plt.xlabel('Date')
        #mpld3.show(fig)**This launches browser with blank page**
        #save_html(fig,'/tmp/%s_%s_trend.html' % (io_type,bs))
        #**also creates a blank html page with JS**
        #fig.savefig('/tmp/%s_%s_trend.svg' % (io_type,bs))**works fine**
        plt.clf()`

**Comment by etgalloway** [comment]
Unfortunately, mpld3 v 0.2 does not support custom date tick locations.  A fix was
merged into master recently: #337.

What do you get if you try current master from GitHub?

To see what can be done with custom date ticks look at test_date_ticks.py in the test_plots directory on GitHub.

**Comment by rcrowe123** [comment]
Tried the latest master from GitHub, but can't seem to build it. 
Following the instructions on the GH page: https://github.com/jakevdp/mpld3

python setup.py submodule
I get this error:
Traceback (most recent call last):
  File "setup.py", line 30, in <module>
    check_js_build_status(VERSION, root_dir)
  File "/home/rcrowe/mpld3/mpld3/_mpld3_setup.py", line 231, in check_js_build_status
    raise ValueError(VERSION_ERROR.format(version))
ValueError: 
# Javascript libraries for mpld3 version 0.3git are missing.
# Please run
#   python setup.py buildjs
# to re-build the javascript libraries.
# This requires npm to be installed: see CONTRIBUTING.md for details.

So I try to run this:
python setup.py buildjs
running buildjs
make javascript
make: node_modules/.bin/smash: Command not found
node_modules/.bin/smash src/mpld3.js | node_modules/.bin/uglifyjs - -b indent-level=2 -o mpld3/js/mpld3.v0.3git.js
/bin/sh: 1: node_modules/.bin/smash: not found
/bin/sh: 1: node_modules/.bin/uglifyjs: not found
make: *** [mpld3/js/mpld3.v0.3git.js] Error 127
command 'make' failed with exit status 2

I have matplotlib 1.3.1, jinja 2.7.2-2 and npm 1.3.10 installed.  I tried to install uglifyjs, but the Ubuntu repo only has node-uglify, but it is installed. I don't see a package called smash in the repo, however I do see this package on GH....https://github.com/hypersoft/smash. Do I need this?
What am I missing?

**Comment by etgalloway** [comment]
The makefile does not install Javascript packages. You need to run `npm install`.  See `Contributing.md`.

A newer version of `npm` might help.  I'm using 3.7.3 on Ubuntu 14.04.
